[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "https://appcrates.netlify.app/*"
  to = "https://appcrates.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://appcrates.netlify.app/*"
  to = "https://appcrates.pl/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/media/favicon.ico"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
